"""add_notification_preferences_to_users

Revision ID: 0d5ab7ec066b
Revises: cf95497aa948
Create Date: 2025-06-27 16:56:26.418048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d5ab7ec066b'
down_revision: Union[str, None] = 'cf95497aa948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add notification preference columns to users table
    op.add_column('users', sa.Column('reminder_notifications', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('users', sa.Column('habit_reminders', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('users', sa.Column('task_deadlines', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('users', sa.Column('weekly_summaries', sa.Boolean(), nullable=True, server_default='true'))
    op.add_column('users', sa.Column('notification_time', sa.String(length=5), nullable=True, server_default='09:00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove notification preference columns from users table
    op.drop_column('users', 'notification_time')
    op.drop_column('users', 'weekly_summaries')
    op.drop_column('users', 'task_deadlines')
    op.drop_column('users', 'habit_reminders')
    op.drop_column('users', 'reminder_notifications')
    # ### end Alembic commands ###
