"""Add missing columns to tasks table

Revision ID: 47fd33329cc7
Revises: 
Create Date: 2025-06-27 01:05:56.033993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47fd33329cc7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habits', sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='habitfrequency'), nullable=True))
    op.add_column('habits', sa.Column('best_streak', sa.Integer(), nullable=True))
    op.add_column('habits', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('notes', sa.Column('tags', sa.String(length=500), nullable=True))
    op.alter_column('reminders', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='reminderstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('reminders', 'is_completed')
    op.add_column('tasks', sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='taskstatus'), nullable=True))
    op.add_column('tasks', sa.Column('tags', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('tasks', 'priority',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               existing_nullable=True)
    op.drop_column('tasks', 'is_completed')
    op.alter_column('users', 'telegram_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus'),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'BANNED', name='userstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('users', 'telegram_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.add_column('tasks', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('tasks', 'priority',
               existing_type=sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskpriority'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('tasks', 'updated_at')
    op.drop_column('tasks', 'tags')
    op.drop_column('tasks', 'status')
    op.add_column('reminders', sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('reminders', 'status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'CANCELLED', name='reminderstatus'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('notes', 'tags')
    op.drop_column('habits', 'updated_at')
    op.drop_column('habits', 'best_streak')
    op.drop_column('habits', 'frequency')
    # ### end Alembic commands ###
